# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 846b803158d62bb0c62005094695916819cb71049664f1865368c8d9f7c71d49b10d707906fc7c5d44de1f78c6e7afb125b53760fe8d36bbccceecec74af4ed0

test:
  secret_key_base: ccaa4a77d7893f186b635c0ccf17a733ceab1634c8b921fd7ed9ea2dd47abb1c93a5ea00d5b06d210f3fdd341f90766c827a02385af404db3fb00f5f70adec91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
