# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27bf16c2440ef0c7510f0a8e8b55e668f3c51790c33718a076f49e142ddc70d0e8f9e12c21dc47a1516abe9dc280989058e7f505bf44f6670cf494f2cc78f07

test:
  secret_key_base: 1d23b0a50900220a135085dd7780b621d2382960d26888d2db5f3bb42dbf7ef3dde044451861b1f118336e355b53e47bc167d6606ee6d4b168ccdd055048e0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
