# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51fa8b439e5985e7834a86f36b79ecb4676167e11a9287ac10411e701e63a73c5678e98698cf7383149e96eb2ac20549acd2850357441fd8c97030f1b6b34956

test:
  secret_key_base: fb47aef561a498de90a43e2bdb49a064a891086b6a3d7ff9cae8b6575a36dc7db657a9df19f3c02956ed181260ed199fa90d282489f81440be6593bdd1c00248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
